backend:
  name: github
  repo: heystevegray/dev-portfolio-netlify-cms
media_folder: static/assets
public_folder: assets
publish_mode: editorial_workflow
collections:
  - name: til
    label: til
    description: Today I Learned
    folder: content/til
    create: true
    slug: "{{slug}}"
    fields:
      - { name: title, label: Title, widget: string }
      - { name: publish_date, label: Publish Date, widget: datetime }
      - { name: updated, label: Updated At, widget: datetime, required: false }
      - { name: description, label: Description, required: false }
      - { name: image, label: Image, widget: image, required: false }
      - { name: body, label: Body, widget: markdown }
      - { name: tldr, label: TLDR, widget: markdown }
      - { name: tags, label: Tags, widget: list }
  - name: projects
    label: projects
    description: Today I Learned
    folder: content/projects
    create: true
    slug: "{{slug}}"
    fields:
      - { name: title, label: Title, widget: string }
      - { name: updated, label: Updated At, widget: datetime }
      - { name: description, label: Description, required: false }
      - { name: image, label: Image, widget: image, required: false }
      - { name: demo, label: Demo Link, widget: string }
      - { name: github, label: Github Link, widget: string, required: false }
      - { name: tags, label: Tags, widget: list }
